channels:
  - conda-forge
dependencies:
  - python=3.9
  - r-base
  - r-ggplot2
  - r-shiny
  - r-msar
  # Python dependencies
  - rpy2
  - matplotlib
  - pandas
  - plotnine
  - ipycytoscape
  - itkwidgets
  - ipywidgets
  - jupyter-lsp
  - jupyter-lsp-python
  - jupyterlab
  - jupyterlab-git
  - jupyterlab-lsp
  - jupyterlab-fasta
  - nglview
  - ipympl
